routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\FollowerController;
use App\Http\Controllers\IdeaController;
use App\Http\Controllers\Admin\DashboardController as AdminDashBoardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[DashboardController::class,'index'])->name('dashboard');
Route::get('/terms',function(){return view('feed');})->name('terms');
Route::resource('users', UserController::class)->only('edit','show','update')->middleware('auth');
Route::get('profile',[UserController::class,'profile'])->name('profile')->middleware('auth');

Route::group(['prefix'=> 'ideas/', 'as'=>'ideas.'], function() {

    Route::post('',[IdeaController::class,'store'])->name('store');
    Route::get('{id}',[IdeaController::class,'show'])->name('show');

    Route::get('{id}/edit',[IdeaController::class,'edit'])->name('edit')->middleware('auth');
    Route::put('{id}',[IdeaController::class,'update'])->name('update')->middleware('auth');

    Route::delete('{id}',[IdeaController::class,'destroy'])->name('destroy')->middleware('auth');





});

// Route::resource('ideas', IdeaController::class)->except(['index','create'])->middleware('auth');

Route::resource('ideas.comments', CommentController::class)->only(['store'])->middleware('auth');


Route::post('users/{user}/follow', [FollowerController::class, 'follow'])->middleware('auth')->name('users.follow');


Route::post('users/{user}/unfollow', [FollowerController::class, 'unfollow'])->middleware('auth')->name('users.unfollow');
// Model

// Model
// controller
// Migration
// routes

Route::get('/feed',[FeedController::class, 'index'])->middleware('auth')->name('feed');

Route::get('/admin',[AdminDashBoardController::class, 'index'])->middleware(['auth','can:admin'])->name('admin.dashboard');

resources/views/shared/comments-box.blade.php
<div>

    <form action="{{ route('ideas.comments.store', $idea->id) }}" method="post">
        @csrf
        <div class="mb-3">
            <textarea name="content" class="fs-6 form-control" rows="1"></textarea>
        </div>

        <div>
            <button type="submit" class="btn btn-primary btn-sm">Post Comment</button>
        </div>
    </form>
    <hr>
    @foreach ($idea->comments as $comment)


    <div class="d-flex align-items-start">
        <img style="width:35px" class="me-2 avatar-sm rounded-circle"
            src="{{$comment->user->getImageURL()}}"
            alt="{{$comment->user->name}}">
        <div class="w-100">
            <div class="d-flex justify-content-between">
                <h6 class="">{{$comment->user->name}}
                </h6>
                <small class="fs-6 fw-light text-muted">{{ $comment->created_at->diffForHumnas() }}</small>
            </div>
            <p class="fs-6 mt-3 fw-light">
                {{ $comment->content }}
            </p>
        </div>
    </div>
    @endforeach

</div>

resources/views/shared/follow-box.blade.php
<div class="card mt-3">
    <div class="card-header pb-0 border-0">
        <h5 class="">Who to follow</h5>
    </div>
    <div class="card-body">
        <div class="hstack gap-2 mb-3">
            <div class="avatar">
                <a href="#!"><img class="avatar-img rounded-circle"
                        src="https://api.dicebear.com/6.x/fun-emoji/svg?seed=Mario" alt=""></a>
            </div>
            <div class="overflow-hidden">
                <a class="h6 mb-0" href="#!">Mario Brother</a>
                <p class="mb-0 small text-truncate">@Mario</p>
            </div>
            <a class="btn btn-primary-soft rounded-circle icon-md ms-auto" href="#"><i
                    class="fa-solid fa-plus"> </i></a>
        </div>
        <div class="hstack gap-2 mb-3">
            <div class="avatar">
                <a href="#!"><img class="avatar-img rounded-circle"
                        src="https://api.dicebear.com/6.x/fun-emoji/svg?seed=Mario" alt=""></a>
            </div>
            <div class="overflow-hidden">
                <a class="h6 mb-0" href="#!">Mario Brother</a>
                <p class="mb-0 small text-truncate">@Mario</p>
            </div>
            <a class="btn btn-primary-soft rounded-circle icon-md ms-auto" href="#"><i
                    class="fa-solid fa-plus"> </i></a>
        </div>
        <div class="d-grid mt-3">
            <a class="btn btn-sm btn-primary-soft" href="#!">Show More</a>
        </div>
    </div>
</div>

resources/views/shared/idea-card.blade.php
<div class="card">
    <div class="px-3 pt-4 pb-2">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img style="width:50px" class="me-2 avatar-sm rounded-circle"
                    src="{{$idea->user->getImageURL()}}" alt="{{ $idea->user->name }}">
                <div>
                    <h5 class="card-title mb-0"><a href="{{route('users.show',$idea->user->id)}}">{{ $idea->user->name }}</a></h5>
                </div>
            </div>

            <div>
                <a class="mx-2" href="{{ route('ideas.show', $idea->id)}}">View</a>
                @auth
                    @can('idea.edit', $idea)
                        <a href="{{ route('ideas.edit', $idea->id) }}">Edit</a>
                    @endcan

                    @can('idea.delete', $idea)
                        <form action="{{ route('ideas.destroy', $idea->id) }}" method="POST">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    @endcan
                @endauth
            </div>
        </div>
    </div>

    <div class="card-body">
        @if($editing ?? false)
            <form action="{{route('ideas.update',$idea->id)}}" method="post">
                @csrf
                @method('put')
                <div class="mb-3">
                    <textarea name= 'content' class="form-control" id="content" rows="3">{{$idea->content}}</textarea>
                    @error('content')
                        <span class="d-block fs-6 text-danger mt-2">{{ $message }}</span>
                    @enderror
                </div>
                <div class="">
                    <button type="Submit" class="btn btn-dark mb-2 btn-small"> Update </button>
                </div>
            </form>
        @else
            <p class="fs-6 fw-light text-muted">
                {{$idea->content}}
            </p>
        @endif
        <div class="d-flex justify-content-between">
            <div>
                <a href="#" class="fw-light nav-link fs-6"> <span class="fas fa-heart me-1"></span> {{$idea->likes}} </a>
            </div>
            <div>
                <span class="fs-6 fw-light text-muted"> <span class="fas fa-clock"> </span> {{$idea->created_at->diffForHumans()}} </span>
            </div>
        </div>
        @include('shared.comments-box')
    </div>
</div>

resources/views/shared/left-sidebar.blade.php
<div class="card overflow-hidden">
    <div class="card-body pt-3">
        <ul class="nav nav-link-secondary flex-column fw-bold gap-2">
            <li class="nav-item">
                <a class="nav-link {{ (Route::is('dashboard')) ? 'text-white bg-primary rounded':'' }}" href="{{route('dashboard')}}">
                    <span>Home</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('feed')}}">
                    <span>Feed</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{route('terms')}}">
                    <span>Terms</span></a>
            </li>

        </ul>
    </div>
    <div class="card-footer text-center py-2">
        <a class="btn btn-link btn-sm" href="{{route('profile')}}">View Profile </a>
    </div>
</div>

resources/views/shared/search-bar.blade.php
<div class="card">
    <div class="card-header pb-0 border-0">
        <h5 class="">Search</h5>
    </div>
    <div class="card-body">
        <form action="{{route('dashboard')}}" method="GET">
            @csrf
        <input placeholder="...
        " class="form-control w-100" type="text"
            name="search" value="{{request('search','')}}">
        <button type="submit" class="btn btn-dark mt-2"> Search</button>
        </form>
    </div>
</div>

resources/views/shared/submit-idea.blade.php
@auth
<h4> Share yours ideas </h4>
<div class="row">
    <form action="{{route('ideas.store')}}" method="post">
     @csrf
        <div class="mb-3">
            <textarea name= 'content' class="form-control" id="idea" rows="3"></textarea>
            @error('idea')
                <span class="d-block fs-6 text-danger mt-2">{{ $message }}</span>
            @enderror
        </div>
        <div class="">
            <button type="Submit" class="btn btn-dark"> Share </button>
        </div>
    </form>
</div>
@endauth

@guest
    <h4>Log in to share your ideas</h4>
@endguest

resources/views/shared/success-message.blade.php
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif

resources/views/shared/user-card.blade.php
<div class="card">
    <div class="px-3 pt-4 pb-2">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <img style="width:150px" class="me-3 avatar-sm rounded-circle"
                    src="{{$user->getImageURL()}}" alt="Mario Avatar">
                <div>

                </div>
            </div>

            <div>
                @auth
                @if(Auth::id() === $user->id)
                <a href="{{route('users.edit',$user->id)}}"><p>Edit</p></a>
                @endif
                @endauth
            </div>

        </div>

            <div class="px-2 mt-4">
                <h5 class="fs-5"> Bio: </h5>

            <p class="fs-6 fw-light">
               {{ $user->bio}}
            </p>

            <div class="d-flex justify-content-start">
                <a href="#" class="fw-light nav-link fs-6 me-3"> <span class="fas fa-user me-1">
                    </span> 0 Followers </a>
                <a href="#" class="fw-light nav-link fs-6 me-3"> <span class="fas fa-brain me-1">
                    </span>{{$user->ideas()->count()}} </a>
                <a href="#" class="fw-light nav-link fs-6"> <span class="fas fa-comment me-1">
                    </span> {{$user->comments()->count()}} </a>
            </div>

             @auth
                @if(Auth::id() !== $user->id)
                    <div class="mt-3">
                        @if (Auth::user()->follows($user))
                        <form method="post" action="{{route('users.unfollow',$user->id)}}">
                            @csrf
                        <button type="submit" class="btn btn-primary btn-sm"> UnFollow </button>
                        </form>

                        @else
                        <form method="post" action="{{route('users.follow',$user->id)}}">
                            @csrf
                        <button type="submit" class="btn btn-primary btn-sm"> Follow </button>
                        </form>
                        @endif
                    </div>
                @endif

            @endauth
        </div>
    </div>
</div>
<hr>

resources/views/shared/user-edit-card.blade.php
<div class="card">
    <div class="px-3 pt-4 pb-2">
        <form  enctype="multipart/form-data" method="post"  action="{{ route('users.update',$user->id)}}">
            @csrf
            @method('put')
            <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                    <img style="width:150px" class="me-3 avatar-sm rounded-circle"
                        src="{{$user->getImageURL()}}" alt="Mario Avatar">
                    <div>

                        <input name="name" value="{{$user->name}}" type="text" class="form-control">
                            @error('name')
                                <span class="danger">{{$message}}</span>
                            @enderror

                    </div>
                </div>

                <div>
                    @auth
                @if(Auth::id() === $user->id)
                    <a href="{{route('users.show',$user->id)}}"><p>View</p></a>
                    @endif
                    @endauth
                </div>

            </div>
            @if($editing ?? false)
            <div >
                <label class="py-3"  for="Profile picture ">Profile picture</label>
                <input type="file" name='image' class="form-control">
                @error('image')
                    <span>{{ $message }}</span>
                @enderror
            </div>
            @endif

                <div class="px-2 mt-4">
                    <h5 class="fs-5"> Bio: </h5>
                    @if($editing ?? false)
                    <div class="mb-3">
                        <textarea name= 'bio' class="form-control" id="content" rows="3">{{$user->bio}}</textarea>
                        @error('bio')
                            <span class="d-block fs-6 text-danger mt-2">{{ $message }}</span>
                        @enderror
                    </div>
                    <input type="submit" value="save">
                    @endif

                <div class="d-flex justify-content-start">
                    <a href="#" class="fw-light nav-link fs-6 me-3"> <span class="fas fa-user me-1">
                        </span> 0 Followers </a>
                    <a href="#" class="fw-light nav-link fs-6 me-3"> <span class="fas fa-brain me-1">
                        </span>{{$user->ideas()->count()}} </a>
                    <a href="#" class="fw-light nav-link fs-6"> <span class="fas fa-comment me-1">
                        </span> {{$user->comments()->count()}} </a>
                </div>


            </div>
        </form>
    </div>
</div>
<hr>